### ISSUE TITLE
Polygons are 2d instead of 3d

### ISSUE THREAD

**Issue by keithrz** [rclark/osm2geojson#2]
I'm getting 2d coordinates for Polygons instead of 3d.  I think there is a bug in line 74 of index.js:

```
coords = [currentFeature.geometry.coordinates];
```

and I think it should be:

```
currentFeature.geometry.coordinates = [currentFeature.geometry.coordinates];
```

Great library!  I needed a good way to convert an OSM file to geoJson objects, preferably using streams.  Using this library plus geojson-stream makes this really easy!  The only other library that I saw that could do streaming was osmium, and that library could not parse my OSM files for some reason.

**Comment by rclark** [comment]
The problems here run deeper than that, unfortunately. See https://github.com/rclark/osm2geojson/issues/5
