### ISSUE TITLE
Wrap node-osmium... or die!

### ISSUE THREAD

**Issue by rclark** [rclark/osm2geojson#5]
This library fails in a number of ways relating to how polygons and multipolygons are represented in OSM data. https://github.com/osmcode/node-osmium does a wonderful job navigating those intricacies, but its streaming API is a bit convoluted. If this library has anything to offer, it would be offering a more straightforward, more node-ish streaming API over node-osmium.

**Comment by keithrz** [comment]
I tried using node-osmium.  Besides the convoluted streaming interface you mention, and the sheer enormity of the library, it just didn't work at all with the OSM files I am working with.  I got validation  errors.  When I get some extra time, I'll try to recreate the issue with an OSM file that doesn't have sensitive client data, and open up an issue in node-osmium.

For now, I've forked osm2geojson and updated the dependencies in package.json in my github fork, and am including the osm2geojson fork in my project's package.json via a github reference.

It's too bad that this library is dead.  I really like how lightweight it is, and how simple it is to stream with it.

**Comment by rclark** [comment]
node-osmium is just a node.js wrapper on the libosmium c++ library, which is used in a number of other applications like osm2pgsql. It would definitely be a good idea to track down exactly why your files are being considered invalid: its entirely possible that its something trivial about the way those files have been generated or extracted.

I haven't worked much with node-osmium's streaming interface but I was planning to have a look today. I'll be keeping my eyes open for a way to wrap that API in a more "node-friendly" one here if possible.
